name: Run Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: show current folder
        run: pwd &&  ls
      - name: get code
        uses: actions/checkout@v6
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-verson: 18
      - name: install dependancies
        run: npm ci
      - name: Run Tests
        run: npm test
